### ISSUE TITLE
ENOENT error in multicouch module when hoodie start -n

### ISSUE THREAD

**Issue by Junkern** [hoodiehq/faq#119]
I just installed hoodie-cli along with couchDb. After making a new hoodie app (```hoodie new xxx```) I am trying to start the app (```hoodie start -n```).
Following error appears:
```
(node) sys is deprecated. Use util instead.
   Initializing...
   CouchDB started: http://127.0.0.1:6003
   Error: spawn D:\Dokumente\Development\Assemble\assemble\node_modules\hoodie-server               
\node_modules\multicouch\bin\erl.exe E
NOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)

Stopping CouchDB...
Error: ENOENT: no such file or directory, open 'D:\Dokumente\Development\Assemble\assemble\data\couch.pid'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at MultiCouch.stop (D:\Dokumente\Development\Assemble\assemble\node_modules\hoodie-server\node_modules\multicouch\li
b\multicouch.js:114:23)
    at Object.exports.stop (D:\Dokumente\Development\Assemble\assemble\node_modules\hoodie-server\lib\couchdb\index.js:1
81:11)
    at process.<anonymous> (D:\Dokumente\Development\Assemble\assemble\node_modules\hoodie-server\lib\couchdb\index.js:7
6:13)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process.exit (node.js:749:17)
    at Domain.<anonymous> (D:\Dokumente\Development\Assemble\assemble\node_modules\hoodie-server\lib\index.js:64:13)
```
I am on node v4.2.2, npm 2.14.10 and hoodie 0.6.3

**Comment by janl** [comment]
How did you install CouchDB?

**Comment by Junkern** [comment]
(Probably forgot to mention I am on windows). I used the windows installer from the couchb website. Moreover, I did not instlal couchdb to the default directory
