### ISSUE TITLE
Getting error on the test app.

### ISSUE THREAD

**Issue by ehelman1** [hoodiehq/faq#131]
When I try and start the test app i get.

PS C:\Users\Edward\Downloads\hoodie\testapp> hoodie start

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.6.3 (node v6.6.0, npm 2.15.11, platform: win32)

Initializing...
(node:12356) DeprecationWarning: sys is deprecated. Use util instead.
CouchDB started: http://127.0.0.1:6003
Error: spawn C:\Users\Edward\Downloads\hoodie\testapp\node_modules\hoodie-server\node_modules\multicouch\bin\erl.e
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Stopping CouchDB...
Error: ENOENT: no such file or directory, open 'C:\Users\Edward\Downloads\hoodie\testapp\data\couch.pid'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at MultiCouch.stop (C:\Users\Edward\Downloads\hoodie\testapp\node_modules\hoodie-server\node_modules\multicouc
    at Object.exports.stop (C:\Users\Edward\Downloads\hoodie\testapp\node_modules\hoodie-server\lib\couchdb\index.
    at process.<anonymous> (C:\Users\Edward\Downloads\hoodie\testapp\node_modules\hoodie-server\lib\couchdb\index.
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:146:15)
    at Domain.<anonymous> (C:\Users\Edward\Downloads\hoodie\testapp\node_modules\hoodie-server\lib\index.js:64:13)
PS C:\Users\Edward\Downloads\hoodie\testapp> cd ../../..

**Comment by gr2m** [comment]
@ehelman1 I’m sorry you run into trouble! 

We are working on a new Hoodie Version which should make things much simpler! 

Can you please try the following.

1. Delete the `hoodie` command line tool with `npm uninstall -g hoodie`
2. Setup a Hoodie project as defined in: https://github.com/hoodiehq/hoodie/#setup The steps might slightly differ for Windows, please let me know if you need any help.

The new Hoodie is much simpler to run on Windows because it has less native dependencies, and soon it will have none at all :)
