### ISSUE TITLE
Can't complete connect remote Hoodies

### ISSUE THREAD

**Issue by udomsak** [hoodiehq/faq#135]
# Architecture

-  Windows 10
-  nodejs window 
-  remote couchdb  docker on Virtualbox 
-  Version: 0.6.3 (node v4.6.0, npm 2.15.11, platform: win32)

# Error
c:\Developments\udomsak>hoodie start

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.6.3 (node v4.6.0, npm 2.15.11, platform: win32)

(node) sys is deprecated. Use util instead.
Initializing...
Using remote CouchDB: http://localhost:5984
Waiting for CouchDB [-*----] SUCCESS

ERR! Error: socket hang up
ERR!     at createHangUpError (_http_client.js:213:15)
ERR!     at Socket.socketOnEnd (_http_client.js:305:23)
ERR!     at emitNone (events.js:72:20)
ERR!     at Socket.emit (events.js:166:7)
ERR!     at endReadableNT (_stream_readable.js:921:12)
ERR!     at nextTickCallbackWith2Args (node.js:442:9)
ERR!     at process._tickDomainCallback (node.js:397:17)
`

**Comment by gr2m** [comment]
Hey there, thanks for reporting the issue!

We are nearly ready to release our new version of Hoodie which should be much more robust than the current one you tried.

Can you please try the following:

1. `npm uninstall --global hoodie-cli` as the new version has no CLI at this point
2. Follow the instructions at https://github.com/hoodiehq/hoodie#setup

I’m very sorry for the confusion, I know the docs at http://docs.hood.ie/ still refer to the old one, we are working on it :)
